ALTER TABLE generieke_technicals
  ADD COLUMN IF NOT EXISTS ema8 DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS ema20 DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS pct_from_ema8 DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS pct_from_ema20 DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS ema8_minus_ema20 DOUBLE PRECISION;
