name: Ronny Dual Strategy Bot

on:
  workflow_dispatch:

jobs:
  run-trading-bots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Installeren
        run: pip install yfinance pandas pandas_ta vaderSentiment newsapi-python python-telegram-bot
      - name: Start Bots
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python bot.py
          python bot2.py
